//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3620
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhservice.nhPhotoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://service.aspirehld.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.aspirehld.com", ConfigurationName="nhPhotoService.PhotoServiceInterfacePortType")]
    public interface PhotoServiceInterfacePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.nhPhotoService.ArrayOfString save(string in0, string in1, string in2, string in3, string in4, string in5, string in6, string in7);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.nhPhotoService.ArrayOfString get(string in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PhotoServiceInterfacePortTypeChannel : nhservice.nhPhotoService.PhotoServiceInterfacePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PhotoServiceInterfacePortTypeClient : System.ServiceModel.ClientBase<nhservice.nhPhotoService.PhotoServiceInterfacePortType>, nhservice.nhPhotoService.PhotoServiceInterfacePortType {
        
        public PhotoServiceInterfacePortTypeClient() {
        }
        
        public PhotoServiceInterfacePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotoServiceInterfacePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceInterfacePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceInterfacePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public nhservice.nhPhotoService.ArrayOfString save(string in0, string in1, string in2, string in3, string in4, string in5, string in6, string in7) {
            return base.Channel.save(in0, in1, in2, in3, in4, in5, in6, in7);
        }
        
        public nhservice.nhPhotoService.ArrayOfString get(string in0) {
            return base.Channel.get(in0);
        }
    }
}
