//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3620
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhservice.NHService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://xfire.medicare.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfFloat", Namespace="http://xfire.medicare.com", ItemName="float")]
    [System.SerializableAttribute()]
    public class ArrayOfFloat : System.Collections.Generic.List<float> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xfire.medicare.com", ConfigurationName="NHService.HisInterfacePortType")]
    public interface HisInterfacePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetS(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetR(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetY1(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetQ(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetP(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetO(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetN(string in0, string in1, string in2, bool in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetM(
                    nhservice.NHService.ArrayOfString in0, 
                    nhservice.NHService.ArrayOfString in1, 
                    nhservice.NHService.ArrayOfString in2, 
                    nhservice.NHService.ArrayOfString in3, 
                    nhservice.NHService.ArrayOfString in4, 
                    nhservice.NHService.ArrayOfString in5, 
                    nhservice.NHService.ArrayOfString in6, 
                    nhservice.NHService.ArrayOfString in7, 
                    nhservice.NHService.ArrayOfString in8, 
                    nhservice.NHService.ArrayOfString in9, 
                    nhservice.NHService.ArrayOfFloat in10, 
                    nhservice.NHService.ArrayOfFloat in11, 
                    nhservice.NHService.ArrayOfFloat in12, 
                    nhservice.NHService.ArrayOfString in13, 
                    nhservice.NHService.ArrayOfString in14, 
                    string in15, 
                    nhservice.NHService.ArrayOfString in16, 
                    nhservice.NHService.ArrayOfString in17, 
                    nhservice.NHService.ArrayOfString in18, 
                    nhservice.NHService.ArrayOfString in19, 
                    nhservice.NHService.ArrayOfString in20, 
                    nhservice.NHService.ArrayOfString in21, 
                    nhservice.NHService.ArrayOfString in22, 
                    nhservice.NHService.ArrayOfString in23);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryYF(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetL(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    string in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    string in9, 
                    string in10, 
                    string in11, 
                    string in12, 
                    string in13, 
                    string in14, 
                    string in15, 
                    string in16, 
                    string in17, 
                    string in18, 
                    string in19);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetK(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetJ(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string tracegetmedicalNoQueryStringValue(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetI(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetH(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetE1(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    string in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    string in9, 
                    string in10, 
                    string in11, 
                    string in12, 
                    string in13, 
                    string in14, 
                    string in15, 
                    string in16, 
                    string in17, 
                    string in18, 
                    string in19, 
                    string in20, 
                    string in21, 
                    string in22, 
                    string in23, 
                    string in24, 
                    string in25);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetG(string in0, string in1, string in2, bool in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryE1(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetF(nhservice.NHService.ArrayOfString in0, nhservice.NHService.ArrayOfString in1, nhservice.NHService.ArrayOfString in2, nhservice.NHService.ArrayOfString in3, nhservice.NHService.ArrayOfString in4, nhservice.NHService.ArrayOfString in5, nhservice.NHService.ArrayOfString in6, nhservice.NHService.ArrayOfString in7, nhservice.NHService.ArrayOfString in8, nhservice.NHService.ArrayOfString in9, nhservice.NHService.ArrayOfFloat in10, nhservice.NHService.ArrayOfFloat in11, nhservice.NHService.ArrayOfFloat in12, nhservice.NHService.ArrayOfString in13);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetE(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    string in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    string in9, 
                    string in10, 
                    string in11, 
                    string in12, 
                    string in13, 
                    string in14, 
                    string in15);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetD(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetB(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceA(string in0, string in1, string in2, string in3, string in4, string in5, string in6);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceB(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetC(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetF1(
                    nhservice.NHService.ArrayOfString in0, 
                    nhservice.NHService.ArrayOfString in1, 
                    nhservice.NHService.ArrayOfString in2, 
                    nhservice.NHService.ArrayOfString in3, 
                    nhservice.NHService.ArrayOfString in4, 
                    nhservice.NHService.ArrayOfString in5, 
                    nhservice.NHService.ArrayOfString in6, 
                    nhservice.NHService.ArrayOfString in7, 
                    nhservice.NHService.ArrayOfString in8, 
                    nhservice.NHService.ArrayOfString in9, 
                    nhservice.NHService.ArrayOfFloat in10, 
                    nhservice.NHService.ArrayOfFloat in11, 
                    nhservice.NHService.ArrayOfFloat in12, 
                    nhservice.NHService.ArrayOfString in13, 
                    nhservice.NHService.ArrayOfString in14, 
                    string in15, 
                    nhservice.NHService.ArrayOfString in16, 
                    nhservice.NHService.ArrayOfString in17, 
                    nhservice.NHService.ArrayOfString in18, 
                    nhservice.NHService.ArrayOfString in19, 
                    nhservice.NHService.ArrayOfString in20, 
                    nhservice.NHService.ArrayOfString in21, 
                    nhservice.NHService.ArrayOfString in22, 
                    nhservice.NHService.ArrayOfString in23);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetA(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetH1(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryE(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryF(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryC(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryD(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceYF(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryI(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryJ(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetV1(string in0, string in1, string in2, int in3, int in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryH(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceTargetB(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceTargetA(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryTargetX(string in0, string in1, string in2, int in3, int in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetBL(nhservice.NHService.ArrayOfString in0, nhservice.NHService.ArrayOfString in1, nhservice.NHService.ArrayOfString in2, nhservice.NHService.ArrayOfString in3, nhservice.NHService.ArrayOfString in4, nhservice.NHService.ArrayOfString in5, nhservice.NHService.ArrayOfString in6, nhservice.NHService.ArrayOfString in7, nhservice.NHService.ArrayOfString in8, nhservice.NHService.ArrayOfString in9, nhservice.NHService.ArrayOfString in10, nhservice.NHService.ArrayOfString in11, nhservice.NHService.ArrayOfString in12, nhservice.NHService.ArrayOfString in13);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryTargetY(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryTargetZ(string in0, string in1, int in2, int in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string traceQueryTargetT(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString traceQueryTargetU(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryTargetV(string in0, string in1, string in2, int in3, int in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        nhservice.NHService.ArrayOfString[] traceQueryTargetW(string in0, string in1, string in2, int in3, int in4);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface HisInterfacePortTypeChannel : nhservice.NHService.HisInterfacePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HisInterfacePortTypeClient : System.ServiceModel.ClientBase<nhservice.NHService.HisInterfacePortType>, nhservice.NHService.HisInterfacePortType {
        
        public HisInterfacePortTypeClient() {
        }
        
        public HisInterfacePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HisInterfacePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisInterfacePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisInterfacePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string traceQueryTargetS(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetS(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetR(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetR(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetY1(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetY1(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetQ(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetQ(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetP(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetP(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetO(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetO(in0, in1, in2);
        }
        
        public string traceQueryTargetN(string in0, string in1, string in2, bool in3) {
            return base.Channel.traceQueryTargetN(in0, in1, in2, in3);
        }
        
        public string traceQueryTargetM(
                    nhservice.NHService.ArrayOfString in0, 
                    nhservice.NHService.ArrayOfString in1, 
                    nhservice.NHService.ArrayOfString in2, 
                    nhservice.NHService.ArrayOfString in3, 
                    nhservice.NHService.ArrayOfString in4, 
                    nhservice.NHService.ArrayOfString in5, 
                    nhservice.NHService.ArrayOfString in6, 
                    nhservice.NHService.ArrayOfString in7, 
                    nhservice.NHService.ArrayOfString in8, 
                    nhservice.NHService.ArrayOfString in9, 
                    nhservice.NHService.ArrayOfFloat in10, 
                    nhservice.NHService.ArrayOfFloat in11, 
                    nhservice.NHService.ArrayOfFloat in12, 
                    nhservice.NHService.ArrayOfString in13, 
                    nhservice.NHService.ArrayOfString in14, 
                    string in15, 
                    nhservice.NHService.ArrayOfString in16, 
                    nhservice.NHService.ArrayOfString in17, 
                    nhservice.NHService.ArrayOfString in18, 
                    nhservice.NHService.ArrayOfString in19, 
                    nhservice.NHService.ArrayOfString in20, 
                    nhservice.NHService.ArrayOfString in21, 
                    nhservice.NHService.ArrayOfString in22, 
                    nhservice.NHService.ArrayOfString in23) {
            return base.Channel.traceQueryTargetM(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15, in16, in17, in18, in19, in20, in21, in22, in23);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryYF(string in0, string in1, string in2) {
            return base.Channel.traceQueryYF(in0, in1, in2);
        }
        
        public string traceQueryTargetL(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    string in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    string in9, 
                    string in10, 
                    string in11, 
                    string in12, 
                    string in13, 
                    string in14, 
                    string in15, 
                    string in16, 
                    string in17, 
                    string in18, 
                    string in19) {
            return base.Channel.traceQueryTargetL(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15, in16, in17, in18, in19);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetK(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetK(in0, in1, in2);
        }
        
        public string traceQueryTargetJ(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetJ(in0, in1, in2);
        }
        
        public string tracegetmedicalNoQueryStringValue(string in0) {
            return base.Channel.tracegetmedicalNoQueryStringValue(in0);
        }
        
        public string traceQueryTargetI(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetI(in0, in1, in2);
        }
        
        public string traceQueryTargetH(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetH(in0, in1, in2);
        }
        
        public string traceQueryTargetE1(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    string in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    string in9, 
                    string in10, 
                    string in11, 
                    string in12, 
                    string in13, 
                    string in14, 
                    string in15, 
                    string in16, 
                    string in17, 
                    string in18, 
                    string in19, 
                    string in20, 
                    string in21, 
                    string in22, 
                    string in23, 
                    string in24, 
                    string in25) {
            return base.Channel.traceQueryTargetE1(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15, in16, in17, in18, in19, in20, in21, in22, in23, in24, in25);
        }
        
        public string traceQueryTargetG(string in0, string in1, string in2, bool in3) {
            return base.Channel.traceQueryTargetG(in0, in1, in2, in3);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryE1(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.traceQueryE1(in0, in1, in2, in3, in4);
        }
        
        public string traceQueryTargetF(nhservice.NHService.ArrayOfString in0, nhservice.NHService.ArrayOfString in1, nhservice.NHService.ArrayOfString in2, nhservice.NHService.ArrayOfString in3, nhservice.NHService.ArrayOfString in4, nhservice.NHService.ArrayOfString in5, nhservice.NHService.ArrayOfString in6, nhservice.NHService.ArrayOfString in7, nhservice.NHService.ArrayOfString in8, nhservice.NHService.ArrayOfString in9, nhservice.NHService.ArrayOfFloat in10, nhservice.NHService.ArrayOfFloat in11, nhservice.NHService.ArrayOfFloat in12, nhservice.NHService.ArrayOfString in13) {
            return base.Channel.traceQueryTargetF(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13);
        }
        
        public string traceQueryTargetE(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    string in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    string in9, 
                    string in10, 
                    string in11, 
                    string in12, 
                    string in13, 
                    string in14, 
                    string in15) {
            return base.Channel.traceQueryTargetE(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15);
        }
        
        public string traceQueryTargetD(string in0, string in1) {
            return base.Channel.traceQueryTargetD(in0, in1);
        }
        
        public string traceQueryTargetB(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetB(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceA(string in0, string in1, string in2, string in3, string in4, string in5, string in6) {
            return base.Channel.traceA(in0, in1, in2, in3, in4, in5, in6);
        }
        
        public nhservice.NHService.ArrayOfString traceB(string in0, string in1, string in2) {
            return base.Channel.traceB(in0, in1, in2);
        }
        
        public string traceQueryTargetC(string in0, string in1, string in2, string in3) {
            return base.Channel.traceQueryTargetC(in0, in1, in2, in3);
        }
        
        public string traceQueryTargetF1(
                    nhservice.NHService.ArrayOfString in0, 
                    nhservice.NHService.ArrayOfString in1, 
                    nhservice.NHService.ArrayOfString in2, 
                    nhservice.NHService.ArrayOfString in3, 
                    nhservice.NHService.ArrayOfString in4, 
                    nhservice.NHService.ArrayOfString in5, 
                    nhservice.NHService.ArrayOfString in6, 
                    nhservice.NHService.ArrayOfString in7, 
                    nhservice.NHService.ArrayOfString in8, 
                    nhservice.NHService.ArrayOfString in9, 
                    nhservice.NHService.ArrayOfFloat in10, 
                    nhservice.NHService.ArrayOfFloat in11, 
                    nhservice.NHService.ArrayOfFloat in12, 
                    nhservice.NHService.ArrayOfString in13, 
                    nhservice.NHService.ArrayOfString in14, 
                    string in15, 
                    nhservice.NHService.ArrayOfString in16, 
                    nhservice.NHService.ArrayOfString in17, 
                    nhservice.NHService.ArrayOfString in18, 
                    nhservice.NHService.ArrayOfString in19, 
                    nhservice.NHService.ArrayOfString in20, 
                    nhservice.NHService.ArrayOfString in21, 
                    nhservice.NHService.ArrayOfString in22, 
                    nhservice.NHService.ArrayOfString in23) {
            return base.Channel.traceQueryTargetF1(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15, in16, in17, in18, in19, in20, in21, in22, in23);
        }
        
        public string traceQueryTargetA(string in0, string in1, string in2, string in3) {
            return base.Channel.traceQueryTargetA(in0, in1, in2, in3);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetH1(string in0, string in1, string in2, string in3) {
            return base.Channel.traceQueryTargetH1(in0, in1, in2, in3);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryE(string in0, string in1, string in2) {
            return base.Channel.traceQueryE(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryF(string in0, string in1, string in2) {
            return base.Channel.traceQueryF(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryC(string in0, string in1, string in2) {
            return base.Channel.traceQueryC(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryD(string in0, string in1, string in2) {
            return base.Channel.traceQueryD(in0, in1, in2);
        }
        
        public string traceYF(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.traceYF(in0, in1, in2, in3, in4, in5);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryI(string in0, string in1, string in2) {
            return base.Channel.traceQueryI(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryJ(string in0, string in1, string in2) {
            return base.Channel.traceQueryJ(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetV1(string in0, string in1, string in2, int in3, int in4) {
            return base.Channel.traceQueryTargetV1(in0, in1, in2, in3, in4);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryH(string in0) {
            return base.Channel.traceQueryH(in0);
        }
        
        public nhservice.NHService.ArrayOfString traceTargetB(string in0, string in1, string in2) {
            return base.Channel.traceTargetB(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceTargetA(string in0, string in1, string in2, string in3) {
            return base.Channel.traceTargetA(in0, in1, in2, in3);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryTargetX(string in0, string in1, string in2, int in3, int in4) {
            return base.Channel.traceQueryTargetX(in0, in1, in2, in3, in4);
        }
        
        public string traceQueryTargetBL(nhservice.NHService.ArrayOfString in0, nhservice.NHService.ArrayOfString in1, nhservice.NHService.ArrayOfString in2, nhservice.NHService.ArrayOfString in3, nhservice.NHService.ArrayOfString in4, nhservice.NHService.ArrayOfString in5, nhservice.NHService.ArrayOfString in6, nhservice.NHService.ArrayOfString in7, nhservice.NHService.ArrayOfString in8, nhservice.NHService.ArrayOfString in9, nhservice.NHService.ArrayOfString in10, nhservice.NHService.ArrayOfString in11, nhservice.NHService.ArrayOfString in12, nhservice.NHService.ArrayOfString in13) {
            return base.Channel.traceQueryTargetBL(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryTargetY(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetY(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryTargetZ(string in0, string in1, int in2, int in3) {
            return base.Channel.traceQueryTargetZ(in0, in1, in2, in3);
        }
        
        public string traceQueryTargetT(string in0, string in1, string in2) {
            return base.Channel.traceQueryTargetT(in0, in1, in2);
        }
        
        public nhservice.NHService.ArrayOfString traceQueryTargetU(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.traceQueryTargetU(in0, in1, in2, in3, in4);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryTargetV(string in0, string in1, string in2, int in3, int in4) {
            return base.Channel.traceQueryTargetV(in0, in1, in2, in3, in4);
        }
        
        public nhservice.NHService.ArrayOfString[] traceQueryTargetW(string in0, string in1, string in2, int in3, int in4) {
            return base.Channel.traceQueryTargetW(in0, in1, in2, in3, in4);
        }
    }
}
